### ISSUE TITLE
Errors when trying to go to albums and other tabs

### ISSUE THREAD

**Issue by MikeDuncan1** [pulsejet/memories#517]
**Describe the bug**
When I go to the Albums tab or almost any other tab I was getting an error.
"n.map is not a function"
I also saw e.map and t.map is not a function depending what tab was open.  It does not do it on regular web browser.  I thought maybe it would fix it if I uninstalled the memories android home link but now memories does not ask me if I want to reinstall it.  How can I trigger that to pop up, is there a place to install the home screen app?

**Platform (please complete the following information):**

- OS: android
- Browser memories home screen app thing
- Version 4.12.4

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache
yes, true even clearing the cache in chrome on android did not help

Is there a way to revert to 4.12.3 for the time being?  It was working perfectly except face thumbs.  Is there a way to trigger the memories home screen app on android?

**Comment by MikeDuncan1** [comment]
![Screenshot_20230324-042004.png](https://user-images.githubusercontent.com/29655039/227501153-949122a2-7d3f-47fc-9918-a3ed7751325f.png)

![Screenshot_20230324-041930.png](https://user-images.githubusercontent.com/29655039/227501262-226c9c1d-3f2f-4e30-a27a-667c92f702d3.png)

**Comment by tstdin** [comment]
I have seen the same error message after upgrading to 4.12.4 in the albums. However, the issue resolved itself after couple of minutes and now it seems to work just fine.

**Comment by MikeDuncan1** [comment]
> I have seen the same error message after upgrading to 4.12.4 in the albums. However, the issue resolved itself after couple of minutes and now it seems to work just fine.

Gosh, I wish I hadn't uninstalled the memories app  XD surely there is a way to get it back

**Comment by pulsejet** [comment]
I think it's "Add to Home screen" in the 3 dot menu in chrome (at least for me) ;)
