### ISSUE TITLE
2.0.0: White screen on loading

### ISSUE THREAD

**Issue by jakobroehrl** [pulsejet/memories#55]
Some errors of the console:
Error: Could not find initial state showHidden of memories
TypeError: e.t is not a function
Error: Could not find initial state showHidden of memories
TypeError: this.timelineTicks is undefined

Last NC 24, Firefox

![image](https://user-images.githubusercontent.com/24530680/192151257-5f52dd30-ee76-4ad4-b0bc-d638f71520f2.png)

**Comment by pulsejet** [comment]
1. What version of Firefox?
2. Did you try clearing cache?
3. Did it work before 2.0?
4. Did you install from the app store or git?

**Comment by jakobroehrl** [comment]
Tested with 2.1.2 again. It's not working with firefox (105.0.1) and brave.
In both browsers same problem: white screen.
Before 2.0 I had no problems.
I installed with the app store

**Comment by pulsejet** [comment]
I can't reproduce, so you've to debug more. Does it work in chromium? Also did you clear browser cache? Does it work on a different device?

**Comment by Civlac** [comment]
Also having this issue after updating from v1.1.6 to 2.1.2 through the NC store. Ran the index command as required, re-processed the files without errors (local external). Cleared local site data, no bueno.

![image](https://user-images.githubusercontent.com/42948607/192356547-2e3d18e1-c314-4c31-b3a4-839669ea3c57.png)

**Comment by Civlac** [comment]
Fixed 👍
I must've missed the note about the path requirement changing. Thanks for the fast reply 😄

**Comment by pulsejet** [comment]
Yeah, unfortunately the Nextcloud app store doesn't have any way to show a changelog when you update apps 🙄

**Comment by jakobroehrl** [comment]
It doesnot work on other devices, too. 
So it must be my system. 
PTP 8.1.2
Mysql 10.8.4

![image](https://user-images.githubusercontent.com/24530680/192436016-6ab94e1d-b1cf-4db4-b0b2-becda15f0552.png)

**Comment by jakobroehrl** [comment]
New photos are shown, but all the old ones are gone I noticed.

**Comment by pulsejet** [comment]
Did you run `occ memories:index --clear` after upgrading?

**Comment by jakobroehrl** [comment]
That was the problem, thank a lot! :)
